# Generated by Django 5.1.1 on 2024-09-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                (
                    "pontuacao",
                    models.FloatField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "preco",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        blank=True, default="N/A", max_length=15, null=True
                    ),
                ),
                (
                    "nanometros",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "ghz",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GPU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                ("pontuacao", models.FloatField(blank=True, default=None, null=True)),
                (
                    "preco",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "tflops",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "memoria",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
                (
                    "gpixels",
                    models.CharField(
                        blank=True, default=None, max_length=200, null=True
                    ),
                ),
            ],
        ),
    ]
