# Generated by Django 5.1.1 on 2024-09-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardwares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gpu",
            name="identifier",
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
