# Generated by Django 5.1.1 on 2024-09-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hardwares", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cpu",
            name="ghz",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="cpu",
            name="nanometros",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="cpu",
            name="preco",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="cpu",
            name="tipo",
            field=models.CharField(default="N/A", max_length=15),
        ),
        migrations.AddField(
            model_name="gpu",
            name="gpixels",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gpu",
            name="memoria",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gpu",
            name="preco",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="gpu",
            name="tflops",
            field=models.FloatField(default=0),
        ),
    ]
